# Generated by Django 5.2.4 on 2025-07-31 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MCQRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_text",
                    models.TextField(
                        help_text="The original text provided by the user for MCQ generation."
                    ),
                ),
                (
                    "generated_mcqs",
                    models.JSONField(
                        help_text="The JSON output containing the generated MCQs."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of when the MCQ request was made.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who generated this MCQ set.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcq_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MCQ Request",
                "verbose_name_plural": "MCQ Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
